---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.kuboard.cn/workload: ckb-explorer-monitor
  labels:
    k8s.kuboard.cn/layer: monitor
    k8s.kuboard.cn/name: ckb-explorer-monitor
  name: ckb-explorer-monitor
  namespace: mainnet
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: monitor
      k8s.kuboard.cn/name: ckb-explorer-monitor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2023-04-29T01:14:55+08:00'
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/layer: monitor
        k8s.kuboard.cn/name: ckb-explorer-monitor
    spec:
      containers:
        - env:
            #ckb-explorer地址，未设置默认地址
            - name: BROWSER_URL
              value: 'http://ckb-explorer-api:3000'
            #接口抓取时间
            - name: TIMEOUT
              value: 10s
          image: 'ghcr.io/magickbase/ckb-explorer-monitor:v0.0.9'
          imagePullPolicy: IfNotPresent
          name: ckb-explorer-monitor
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/workload: ckb-explorer-monitor
  labels:
    k8s.kuboard.cn/layer: monitor
    k8s.kuboard.cn/name: ckb-explorer-monitor
  name: ckb-explorer-monitor
  namespace: mainnet
spec:
  ports:
    - name: ckb-explorer-monitor
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    k8s.kuboard.cn/layer: monitor
    k8s.kuboard.cn/name: ckb-explorer-monitor
  sessionAffinity: None
  type: ClusterIP

